### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Karen-Ardila** [LucasCarioca/wedding-registration-guest#1]
The landing page should have the following options:

- Home
- Schedule
- Travel
- Registry
- Gallery
- Things to do
- FAQs
- Adding inspiration URL: https://www.wix.com/website-template/view/html/1881?siteId=2a20021f-7fda-4004-95e7-938cd877f036&metaSiteId=b68d6c1a-53cf-4864-8e5a-714b942445e8&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fevents%2Fweddings&tpClick=view_button
look and feel should be like the screeshot below:

<img width="1593" alt="Screen Shot 2022-05-09 at 9 52 54 PM" src="https://user-images.githubusercontent.com/67566588/167533376-dabaaf59-0b27-4a18-9511-731804a44d83.png">

**Comment by LucasCarioca** [comment]
this is complete
